# Makefile para compilar y ejecutar programa1 y programa2 en Erlang

ERL=erl
ERLC=erlc
ERLFLAGS=

.PHONY: all ejecutar_programa1 ejecutar_programa2 limpiar

all: ejercicio1.beam ejercicio1.beam ejercicio1.beam ejercicio1.beam ejercicio1.beam ejercicio1.beam ejercicio1.beam ejercicio1.beam ejercicio1.beam ejercicio1.beam ejercicio1.beam ejercicio1.beam ejercicio1.beam ejercicio1.beam ejercicio1.beam ejercicio1.beam ejercicio1.beam ejercicio20.beam ejercicio21.beam ejercicio22.beam ejercicio23.beam ejercicio24.beam

programa1.beam: programa1.erl
	$(ERLC) $(ERLFLAGS) programa1.erl

programa2.beam: programa2.erl
	$(ERLC) $(ERLFLAGS) programa2.erl

ejecutar_programa1: programa1.beam
	$(ERL) -noshell -s programa1 start -s init stop

ejecutar_programa2: programa2.beam
	$(ERL) -noshell -s programa2 start -s init stop

limpiar:
	rm -f *.beam
